import "./ActivityRingsWidget"
import "./StatsSummaryWidget"
import "./ConsistencyHeatmapWidget"
// Recently Grown archived for now — unregistered so it drops from all layouts.
// import "./RecentlyGrownWidget"
import "./TodayVsYesterdayWidget"
import "./NotebookStatsWidget"
import "./LevelProgressWidget"
import "./StreakCardWidget"
import "./SpeciesCollectionWidget"
import "./GroveOverviewWidget"
import "./WeeklySummaryWidget"
import "./FocusDistributionWidget"
import "./InventoryPreviewWidget"
import "./AchievementProgressWidget"
import "./WeekForestWidget"
