// Curated school list for the competition picker. Users can also type a custom name.
export const SCHOOLS: string[] = [
  'UC San Diego',
  'UC Berkeley',
  'UC Los Angeles',
  'UC Irvine',
  'UC Davis',
  'UC Santa Barbara',
  'UC Santa Cruz',
  'UC Riverside',
  'UC Merced',
  'Stanford University',
  'Harvard University',
  'MIT',
  'Yale University',
  'Princeton University',
  'Columbia University',
  'Cornell University',
  'University of Washington',
  'University of Texas at Austin',
  'University of Michigan',
  'New York University',
  'University of Southern California',
  'Georgia Tech',
  'Carnegie Mellon University',
  'University of Toronto',
  'University of Waterloo',
]
